spring.application.name=waste-management

# MongoDB Atlas — database: app (collections e.g. waste_reports use this DB)
spring.data.mongodb.uri=mongodb://samarth25:samarth25@ac-vvu8wt6-shard-00-00.ofmwdmt.mongodb.net:27017,ac-vvu8wt6-shard-00-01.ofmwdmt.mongodb.net:27017,ac-vvu8wt6-shard-00-02.ofmwdmt.mongodb.net:27017/app?ssl=true&replicaSet=atlas-9s1gxt-shard-0&authSource=admin&appName=Cluster0
spring.data.mongodb.database=app

app.upload-dir=uploads

# Firebase auth settings
app.firebase.service-account-path=
app.firebase.web-client-id=
app.firebase.api-key=AIzaSyDNjMu37XLYU14hX-CD1yHEeCZl0xmhOeQ
